package br.edu.ufsc.compilador.analisadores;

public interface ParserConstants
{
    String[] PARSER_ERROR =
    {
        "",
        "Era esperado fim de programa",
        "Era esperado id",
        "Era esperado num_int",
        "Era esperado num_real",
        "Era esperado literal",
        "Era esperado var",
        "Era esperado caracter",
        "Era esperado cadeia",
        "Era esperado inteiro",
        "Era esperado booleano",
        "Era esperado se",
        "Era esperado entao",
        "Era esperado senao",
        "Era esperado leia",
        "Era esperado escreva",
        "Era esperado ou",
        "Era esperado e",
        "Era esperado nao",
        "Era esperado falso",
        "Era esperado verdadeiro",
        "Era esperado de",
        "Era esperado faca",
        "Era esperado real",
        "Era esperado vetor",
        "Era esperado enquanto",
        "Era esperado programa",
        "Era esperado const",
        "Era esperado metodo",
        "Era esperado ref",
        "Era esperado val",
        "Era esperado registro",
        "Era esperado retorne",
        "Era esperado div",
        "Era esperado \";\"",
        "Era esperado \",\"",
        "Era esperado \".\"",
        "Era esperado \">\"",
        "Era esperado \"<\"",
        "Era esperado \"=\"",
        "Era esperado \"(\"",
        "Era esperado \")\"",
        "Era esperado \"[\"",
        "Era esperado \"]\"",
        "Era esperado \"+\"",
        "Era esperado \"-\"",
        "Era esperado \"*\"",
        "Era esperado \"/\"",
        "Era esperado \":\"",
        "Era esperado \":=\"",
        "Era esperado \"..\"",
        "Era esperado \"<>\"",
        "Era esperado \"<=\"",
        "Era esperado \">=\"",
        "Era esperado \"{\"",
        "Era esperado \"}\"",
        "<programa> inválido",
        "<bloco> inválido",
        "<dcl_const> inválido",
        "<dcl_var> inválido",
        "<dcl_metodos> inválido",
        "<dcl_metodo> inválido",
        "<par_formais> inválido",
        "<rep_par> inválido",
        "<tipo_metodo> inválido",
        "<lid> inválido",
        "<rep_lid> inválido",
        "<mp_par> inválido",
        "<tipo> inválido",
        "<constante> inválido",
        "<tipo_pre_definido> inválido",
        "<lista_com> inválido",
        "<rep_lista_com> inválido",
        "<comando> inválido",
        "<senaoparte> inválido",
        "<rcomid> inválido",
        "<rep_expr> inválido",
        "<expressao> inválido",
        "<resto_expressao> inválido",
        "<oprel> inválido",
        "<expsimp> inválido",
        "<rep_expsimp> inválido",
        "<op_add> inválido",
        "<termo> inválido",
        "<rep_termo> inválido",
        "<op_mult> inválido",
        "<fator> inválido",
        "<var> inválido",
        "<rvar> inválido",
        "<constante_explicita> inválido"
    };
}
